#!/usr/bin/env node
// codemap.mjs — standalone implementation of the update-codemap skill.
// Spec source-of-truth: skills/update-codemap/SKILL.md.
// Callable from Claude Code (via the skill) and Copilot (via .github/prompts/update-codemap.prompt.md).

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { extractWithTreeSitter, isTreeSitterLang, initTreeSitter } from './treesitter.mjs';

const SKIP_DIRS = new Set([
  'node_modules', 'bower_components', 'vendor', 'third_party',
  'dist', 'build', 'out', 'target', 'bin', 'obj',
  '.git', '.svn', '.hg', '.idea', '.vscode', '.vs',
  '__pycache__', '.pytest_cache', '.mypy_cache',
  'coverage', '.nyc_output',
  '.next', '.nuxt', '.svelte-kit',
  '.smoke-tmp', '.smoke-out',
]);

const SKIP_FILE_PATTERNS = [
  /\.lock$/i, /\.log$/i, /\.min\.[^/]+$/i, /\.map$/i,
  /\.gen\.cs$/i, /\.g\.cs$/i, /\.generated\./i, /\.designer\.cs$/i,
  /\.meta$/i,
];

const SKIP_FILENAMES = new Set([
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'Cargo.lock', 'Gemfile.lock', 'poetry.lock',
  'Thumbs.db', '.DS_Store', 'desktop.ini', 'nul',
  '.gitignore', '.gitattributes', '.editorconfig',
  // Submodule/worktree pointer files (regular files, not dirs).
  '.git', '.svn', '.hg',
]);

const SKIP_FILENAME_PREFIXES = ['.prettierrc', '.eslintrc'];

const GENERATED_MARKERS = ['@generated', 'DO NOT EDIT', '// <auto-generated>'];

const READ_CAP_LINES = 80;
const READ_CAP_EXTENDED = 200;
const PURPOSE_MAX = 100;
const SIGNATURE_MAX = 120;

const LANG_BY_EXT = {
  '.h': 'cpp-header', '.hpp': 'cpp-header', '.hxx': 'cpp-header', '.hh': 'cpp-header',
  '.cpp': 'cpp-impl', '.cc': 'cpp-impl', '.cxx': 'cpp-impl',
  '.cs': 'csharp',
  '.ts': 'ts', '.tsx': 'ts', '.js': 'ts', '.jsx': 'ts', '.mjs': 'ts', '.cjs': 'ts',
  '.py': 'python',
  '.java': 'java',
  '.kt': 'kotlin', '.kts': 'kotlin',
  '.swift': 'swift',
  '.rs': 'rust',
  '.go': 'go',
  '.html': 'web', '.htm': 'web', '.css': 'web', '.scss': 'web', '.sass': 'web', '.less': 'web',
  '.md': 'markdown', '.mdx': 'markdown',
};

// Internal lang tag → tree-sitter engine grammar tag. cpp-header/cpp-impl both use the
// `cpp` grammar; the rest map 1:1 to themselves (and only the AST-supported set is routed).
const TREE_SITTER_TAG = {
  python: 'python', java: 'java', kotlin: 'kotlin', swift: 'swift',
  rust: 'rust', go: 'go', 'cpp-header': 'cpp', 'cpp-impl': 'cpp',
};

function parseArgs(argv) {
  const args = { root: null, dryRun: false, quiet: false };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') args.dryRun = true;
    else if (a === '--quiet') args.quiet = true;
    else if (a === '--root') args.root = argv[++i];
    else if (a === '--help' || a === '-h') {
      console.log('usage: node skills/update-codemap/codemap.mjs [--root <dir>] [--dry-run] [--quiet]');
      process.exit(0);
    } else if (!args.root) args.root = a;
  }
  args.root = path.resolve(args.root || process.env.CLAUDE_PROJECT_DIR || process.cwd());
  return args;
}

function log(args, msg) { if (!args.quiet) process.stdout.write(msg + '\n'); }

function readProjectName(root) {
  try {
    const readme = path.join(root, 'README.md');
    if (fs.existsSync(readme)) {
      const first = fs.readFileSync(readme, 'utf8').split(/\r?\n/).find((l) => /^#\s+/.test(l));
      if (first) return first.replace(/^#\s+/, '').trim();
    }
  } catch {}
  try {
    const pkg = path.join(root, 'package.json');
    if (fs.existsSync(pkg)) {
      const j = JSON.parse(fs.readFileSync(pkg, 'utf8'));
      if (j.name) return String(j.name).trim();
    }
  } catch {}
  try {
    const csprojs = fs.readdirSync(root).filter((f) => f.endsWith('.csproj'));
    if (csprojs.length) {
      const x = fs.readFileSync(path.join(root, csprojs[0]), 'utf8');
      const m = x.match(/<AssemblyName>([^<]+)<\/AssemblyName>/);
      if (m) return m[1].trim();
    }
  } catch {}
  return path.basename(root);
}

function loadConfig(root) {
  const cfgPath = path.join(root, '.claude', 'codemap.config.md');
  const out = { skipPatterns: [], layers: [], vendoredPatterns: [], autoUpdateEnabled: false, warnings: [] };
  if (!fs.existsSync(cfgPath)) return out;
  const lines = fs.readFileSync(cfgPath, 'utf8').split(/\r?\n/);
  let section = null;
  let lineNo = 0;
  for (const raw of lines) {
    lineNo++;
    const line = raw;
    const h = line.match(/^##\s+(.+?)\s*$/);
    if (h) { section = h[1].trim(); continue; }
    if (!section) continue;
    if (section === 'Skip') {
      const m = line.match(/^\s*-\s*`([^`]+)`\s*$/);
      if (m) out.skipPatterns.push(m[1]);
      else if (/^\s*-\s*`/.test(line)) out.warnings.push({ line: lineNo, text: line });
    } else if (section === 'Layers') {
      const m = line.match(/^\s*-\s*([^:]+):\s*(.+)$/);
      if (m) out.layers.push({ name: m[1].trim(), modules: m[2].split(',').map((s) => s.trim()).filter(Boolean) });
    } else if (section === 'Vendored') {
      const m = line.match(/^\s*-\s*`([^`]+)`\s*$/);
      if (m) out.vendoredPatterns.push(m[1]);
      else if (/^\s*-\s*`/.test(line)) out.warnings.push({ line: lineNo, text: line });
    } else if (section === 'Auto-update') {
      if (/^\s*-?\s*enabled\s*:\s*true\s*$/i.test(line)) out.autoUpdateEnabled = true;
    }
  }
  return out;
}

function configGlobToRegex(pattern) {
  // gitignore-style: trailing / matches dir, ** crosses segments, * single segment.
  const isDir = pattern.endsWith('/');
  const p = isDir ? pattern.slice(0, -1) : pattern;
  let re = '';
  let i = 0;
  while (i < p.length) {
    const c = p[i];
    if (c === '*' && p[i + 1] === '*') { re += '.*'; i += 2; }
    else if (c === '*') { re += '[^/]*'; i++; }
    else if (c === '?') { re += '[^/]'; i++; }
    else if (/[.+^${}()|[\]\\]/.test(c)) { re += '\\' + c; i++; }
    else { re += c; i++; }
  }
  if (isDir) re += '(/.*)?';
  return new RegExp('(^|/)' + re + '$');
}

function walk(root, configSkipRegexes) {
  const files = [];
  function recur(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const ent of entries) {
      const abs = path.join(dir, ent.name);
      const rel = path.relative(root, abs).replace(/\\/g, '/');
      if (ent.isDirectory()) {
        if (SKIP_DIRS.has(ent.name)) continue;
        if (configSkipRegexes.some((re) => re.test(rel + '/'))) continue;
        recur(abs);
      } else if (ent.isFile()) {
        if (SKIP_FILENAMES.has(ent.name)) continue;
        if (SKIP_FILENAME_PREFIXES.some((p) => ent.name.startsWith(p))) continue;
        if (SKIP_FILE_PATTERNS.some((re) => re.test(ent.name))) continue;
        if (configSkipRegexes.some((re) => re.test(rel))) continue;
        files.push({ abs, rel });
      }
    }
  }
  recur(root);
  return files;
}

function readHead(absPath, lines) {
  try {
    const text = fs.readFileSync(absPath, 'utf8');
    const split = text.split(/\r?\n/);
    return { lines: split.slice(0, lines), totalLines: split.length, text };
  } catch {
    return { lines: [], totalLines: 0, text: '' };
  }
}

// Full file text for AST parsing (tree-sitter needs the whole tree, not a capped head).
function readFull(absPath) {
  try { return fs.readFileSync(absPath, 'utf8'); } catch { return ''; }
}

function isGenerated(headLines) {
  const probe = headLines.slice(0, 10).join('\n');
  return GENERATED_MARKERS.some((m) => probe.includes(m));
}

function derivePurpose(headLines, filename) {
  for (let i = 0; i < Math.min(headLines.length, 20); i++) {
    const l = headLines[i].trim();
    if (!l) continue;
    let m;
    if ((m = l.match(/^\/\/\s*(.+)$/))) return clip(m[1].trim());
    if ((m = l.match(/^#\s+(.+)$/))) return clip(m[1].trim());
    if ((m = l.match(/^\/\*\s*(.+?)\s*\*\/?$/))) return clip(m[1].trim());
    if ((m = l.match(/^\*\s*(.+)$/))) return clip(m[1].trim());
    if ((m = l.match(/^"""\s*(.+?)(?:"""|$)/))) return clip(m[1].trim());
    if ((m = l.match(/^---\s*$/))) break;
    if (!l.startsWith('//') && !l.startsWith('#') && !l.startsWith('/*') && !l.startsWith('*')) break;
  }
  return clip(path.parse(filename).name.replace(/[-_]+/g, ' '));
}

function clip(s) {
  s = s.replace(/[.\s]+$/, '');
  return s.length > PURPOSE_MAX ? s.slice(0, PURPOSE_MAX - 1) + '…' : s;
}

function trimSig(s) {
  s = s.trim().replace(/\s+/g, ' ');
  return s.length > SIGNATURE_MAX ? s.slice(0, SIGNATURE_MAX - 1) + '…' : s;
}

// Drop everything from the first unmatched-context `=` onward.
// Used for `const|let|var|type|enum` exports where the line tail is `= <expr>`
// implementation detail that leaks brackets / commas / quotes into the export name.
function stripRhsValue(rest) {
  const eq = rest.indexOf('=');
  if (eq < 0) return rest;
  // Allow `==` / `=>` / `>=` etc. inside type annotations before the binding `=`:
  // step forward to the first `=` that is not part of a multi-char operator.
  let i = 0;
  while (i < rest.length) {
    if (rest[i] === '=' && rest[i + 1] !== '=' && rest[i + 1] !== '>' && rest[i - 1] !== '!' && rest[i - 1] !== '<' && rest[i - 1] !== '>' && rest[i - 1] !== '=') {
      return rest.slice(0, i);
    }
    i++;
  }
  return rest;
}

// Clip a signature tail at the first unmatched opener of `({[`.
// Keeps balanced groups like `(a, b)` intact, but drops `(` with no closer
// (which is what happens when the declaration spans multiple lines).
function clipUnbalancedTail(s) {
  const stack = [];
  const pairs = { ')': '(', ']': '[', '}': '{' };
  let cut = -1;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (c === '(' || c === '[' || c === '{') stack.push(c);
    else if (c === ')' || c === ']' || c === '}') {
      if (stack[stack.length - 1] === pairs[c]) stack.pop();
      else { cut = i; break; }
    }
  }
  if (stack.length && cut < 0) {
    // Find the last opener with no closer and cut there.
    let depth = 0;
    for (let i = s.length - 1; i >= 0; i--) {
      const c = s[i];
      if (c === ')' || c === ']' || c === '}') depth++;
      else if (c === '(' || c === '[' || c === '{') {
        if (depth === 0) { cut = i; break; }
        depth--;
      }
    }
  }
  return cut >= 0 ? s.slice(0, cut).replace(/[\s,]+$/, '') : s;
}

function extractExportsTs(text) {
  const out = [];
  const seen = new Set();
  const push = (name) => { if (name && !seen.has(name)) { seen.add(name); out.push({ name }); } };

  const re = /^export\s+(?:default\s+)?(?:async\s+)?(function\*?|class|interface|type|enum|const|let|var)\s+([A-Za-z_$][\w$]*)([^\n]*)/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    const kind = m[1], name = m[2], rest = m[3];
    const isDefault = /^export\s+default/.test(m[0]);
    // Value bindings: drop RHS entirely so `= z.object({...` doesn't leak in.
    const isValueBinding = kind === 'const' || kind === 'let' || kind === 'var' || kind === 'type' || kind === 'enum';
    let tail = isValueBinding ? stripRhsValue(rest) : rest.replace(/\{.*$/, '');
    tail = clipUnbalancedTail(tail);
    const sig = trimSig(tail);
    push((isDefault ? `default: ${name}` : name) + (sig ? ` — ${sig}` : ''));
  }
  const defAnon = /^export\s+default\s+(?:async\s+)?function\s*\(([^)]*)\)/gm;
  while ((m = defAnon.exec(text)) !== null) {
    push(`default: <anonymous>(${trimSig(m[1])})`);
  }
  const grouped = /^export\s*\{([^}]+)\}/gm;
  while ((m = grouped.exec(text)) !== null) {
    for (const part of m[1].split(',')) {
      const p = part.trim();
      if (!p) continue;
      const asMatch = p.match(/^[A-Za-z_$][\w$]*\s+as\s+([A-Za-z_$][\w$]*)/);
      push(asMatch ? asMatch[1] : p.replace(/\s+as\s+default\s*$/, '').trim());
    }
  }
  const star = /^export\s*\*\s*from\s*['"]([^'"]+)['"]/gm;
  while ((m = star.exec(text)) !== null) push(`re-exports from ${m[1]}`);
  return out;
}

function extractExportsCSharp(text) {
  const out = [];
  const seen = new Set();
  const push = (name) => { if (name && !seen.has(name)) { seen.add(name); out.push({ name }); } };

  const re = /\bpublic\s+(?:static\s+|readonly\s+|sealed\s+|abstract\s+|partial\s+)*(class|struct|interface|enum|record)\s+([A-Za-z_]\w*)/g;
  let m;
  while ((m = re.exec(text)) !== null) push(`${m[1]} ${m[2]}`);
  const method = /\bpublic\s+(?:static\s+|virtual\s+|override\s+|async\s+|sealed\s+)*([A-Za-z_<>][\w<>\[\],\s.]*?)\s+([A-Za-z_]\w*)\s*\(([^)]*)\)/g;
  while ((m = method.exec(text)) !== null) {
    const ret = m[1].trim(), name = m[2], params = m[3].trim();
    if (/^(class|struct|interface|enum|record|new|return|if|for|while|switch)$/.test(name)) continue;
    push(`${name}(${trimSig(params)}): ${trimSig(ret)}`);
  }
  return out;
}

function extractExportsCppHeader(text) {
  const out = [];
  const seen = new Set();
  const push = (name) => { if (name && !seen.has(name)) { seen.add(name); out.push({ name }); } };

  const re = /^(?:class|struct)\s+([A-Za-z_]\w*)/gm;
  let m;
  while ((m = re.exec(text)) !== null) push(m[0].trim());
  const fn = /^(?:[A-Za-z_][\w:<>,\s*&]*\s+)?([A-Za-z_]\w*)\s*\(([^)]*)\)\s*;/gm;
  while ((m = fn.exec(text)) !== null) push(`${m[1]}(${trimSig(m[2])})`);
  return out;
}

// ----- Class graph extraction (phase 1a/1b) -----
// Returns [{ name, kind, extends, implements, fields, namespace, attributes }]
// Used by `## Class graph` consumers (codemap-visualize UML + update-codemap convention detector).

function extractClassesTs(text) {
  const out = [];
  // Match `export? abstract? class|interface Name<T> extends Base implements I, J { ... }` up to the opening brace.
  const re = /\b(?:export\s+(?:default\s+)?)?(?:abstract\s+)?(class|interface)\s+([A-Za-z_$][\w$]*)(?:\s*<[^>]*>)?\s*((?:extends\s+[A-Za-z_$][\w$.<>,\s]*?)?)\s*((?:implements\s+[A-Za-z_$][\w$.<>,\s]*?)?)\s*\{/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    // Reject matches inside a string / template literal. Cheap heuristic:
    // if the line containing the match has a backtick or quote before `class` / `interface`
    // and not closed before the keyword, skip.
    const lineStart = text.lastIndexOf('\n', m.index) + 1;
    const lineHead = text.slice(lineStart, m.index);
    if (isInsideStringOrTemplate(lineHead)) continue;

    const kind = m[1];
    const name = m[2];
    const ext = m[3].replace(/^extends\s+/, '').trim();
    const impl = m[4].replace(/^implements\s+/, '').trim();
    const extendsList = ext ? splitTypeList(ext) : [];
    const implementsList = impl ? splitTypeList(impl) : [];

    // Public class fields — `public foo: Bar;` / `readonly foo: Bar`. TS exposes via public/readonly.
    const bodyStart = m.index + m[0].length;
    const body = sliceBalanced(text, bodyStart - 1);
    const fieldRe = /^\s*(?:public\s+|readonly\s+)+([A-Za-z_$][\w$]*)\s*[?!]?\s*:\s*([A-Za-z_$][\w$.<>,\s|&\[\]]*?)\s*[;=]/gm;
    const fields = [];
    let fm;
    while ((fm = fieldRe.exec(body)) !== null) {
      fields.push({ name: fm[1], type: normalizeTypeRef(fm[2]) });
    }

    out.push({ name, kind, extends: extendsList, implements: implementsList, fields, namespace: '', attributes: [] });
  }
  return out;
}

// Naïve detector: an odd number of unescaped backticks/quotes before the position
// implies the position is inside a string. Good enough to suppress class-keyword
// matches inside template literals.
function isInsideStringOrTemplate(prefix) {
  let inBacktick = false, inSingle = false, inDouble = false;
  for (let i = 0; i < prefix.length; i++) {
    const c = prefix[i];
    if (prefix[i - 1] === '\\') continue;
    if (!inSingle && !inDouble && c === '`') inBacktick = !inBacktick;
    else if (!inBacktick && !inDouble && c === "'") inSingle = !inSingle;
    else if (!inBacktick && !inSingle && c === '"') inDouble = !inDouble;
  }
  return inBacktick || inSingle || inDouble;
}

function extractClassesCSharp(text) {
  const out = [];
  // Capture file-scoped or block namespace.
  const nsMatch = text.match(/^\s*namespace\s+([A-Za-z_][\w.]*)\s*[;{]/m);
  const namespace = nsMatch ? nsMatch[1] : '';

  // Match `[Attr] public abstract? class|struct|interface|record Name<T> : Base, I, J { ... }`
  const re = /((?:^[ \t]*\[[^\]]+\][ \t]*\r?\n)*)[ \t]*(?:public\s+|internal\s+)?(?:static\s+|readonly\s+|sealed\s+|abstract\s+|partial\s+)*(class|struct|interface|enum|record)\s+([A-Za-z_]\w*)(?:\s*<[^>]*>)?\s*(?::\s*([^\{]+?))?\s*(?:where\s+[^{]+)?\s*\{/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    const attrBlock = m[1] || '';
    const kind = m[2];
    const name = m[3];
    const inheritList = m[4] ? splitTypeList(m[4]) : [];
    // C# convention: first entry is base class if it doesn't start with `I[A-Z]`; rest are interfaces.
    // It's not airtight (e.g. ICustom is allowed as base), but it's the standard tell.
    const extendsList = [];
    const implementsList = [];
    if (kind === 'interface' || kind === 'enum') {
      // Interface inheritance + enum base type — keep as `extends`.
      for (const t of inheritList) extendsList.push(t);
    } else {
      for (let i = 0; i < inheritList.length; i++) {
        const t = inheritList[i];
        if (i === 0 && !/^I[A-Z]/.test(t)) extendsList.push(t);
        else implementsList.push(t);
      }
    }

    const attributes = [...attrBlock.matchAll(/\[\s*([A-Za-z_][\w.]*)/g)].map((x) => x[1]);

    // Public fields / auto-properties — `public Foo Bar { get; }` or `public Foo Bar;`.
    const bodyStart = m.index + m[0].length;
    const body = sliceBalanced(text, bodyStart - 1);
    const fieldRe = /^\s*(?:public\s+|protected\s+internal\s+)(?:static\s+|readonly\s+|virtual\s+|override\s+|abstract\s+)*([A-Za-z_][\w.<>,\s\[\]?]*?)\s+([A-Za-z_]\w*)\s*[{;=]/gm;
    const fields = [];
    let fm;
    while ((fm = fieldRe.exec(body)) !== null) {
      const fieldType = normalizeTypeRef(fm[1]);
      const fieldName = fm[2];
      // Skip method matches (those have `(` after the name).
      const after = body.slice(fm.index + fm[0].length - 1, fm.index + fm[0].length + 4);
      if (after.startsWith('(')) continue;
      // Skip C# language keywords accidentally matched as types.
      if (/^(void|return|new|if|for|while|switch|using|class|struct|interface|enum|record)$/.test(fieldType)) continue;
      fields.push({ name: fieldName, type: fieldType });
    }

    out.push({ name, kind, extends: extendsList, implements: implementsList, fields, namespace, attributes });
  }
  return out;
}

function extractClassesCpp(text) {
  const out = [];
  // C++ `class|struct Name : public Base, virtual private Other { ... }`.
  const re = /^(?:template\s*<[^>]*>\s*)?(class|struct)\s+([A-Za-z_]\w*)(?:\s*:\s*([^\{]+?))?\s*\{/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    const kind = m[1];
    const name = m[2];
    const inheritList = m[3]
      ? splitTypeList(m[3]).map((t) => t.replace(/^(public|protected|private|virtual)\s+/g, '').replace(/^(public|protected|private|virtual)\s+/g, '').trim())
      : [];
    // C++ doesn't distinguish extends vs implements at the language level. Surface as extends.
    out.push({ name, kind, extends: inheritList, implements: [], fields: [], namespace: '', attributes: [] });
  }
  return out;
}

// `Foo<A,B>, IBar, Baz` → ['Foo<A,B>', 'IBar', 'Baz']  (commas inside <> not split)
function splitTypeList(s) {
  const out = [];
  let depth = 0;
  let buf = '';
  for (const c of s) {
    if (c === '<' || c === '(' || c === '[') depth++;
    else if (c === '>' || c === ')' || c === ']') depth--;
    if (c === ',' && depth === 0) {
      const t = buf.trim();
      if (t) out.push(t);
      buf = '';
    } else buf += c;
  }
  const t = buf.trim();
  if (t) out.push(t);
  return out;
}

// Strip generic parameters / array brackets / nullability for plain identifier graphing.
// Keeps the head identifier: `Func<Task<object>>` → `Func`. `IReadOnlyList<string>` → `IReadOnlyList`.
function normalizeTypeRef(t) {
  return t.trim().replace(/<.*$/, '').replace(/[\[\]?!]/g, '').trim();
}

// Read text from `text[fromIndex]` (which must be `{`) to its matching `}`. Returns the inside.
function sliceBalanced(text, fromIndex) {
  if (text[fromIndex] !== '{') return '';
  let depth = 0;
  for (let i = fromIndex; i < text.length; i++) {
    const c = text[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return text.slice(fromIndex + 1, i);
    }
  }
  return text.slice(fromIndex + 1);
}

function extractImports(text, lang) {
  const targets = [];
  if (lang === 'ts') {
    const re1 = /\bimport\s+(?:[^'"`]+\s+from\s+)?['"]([^'"]+)['"]/g;
    const re2 = /\brequire\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
    let m;
    while ((m = re1.exec(text)) !== null) targets.push(m[1]);
    while ((m = re2.exec(text)) !== null) targets.push(m[1]);
  } else if (lang === 'csharp') {
    const re = /^using\s+([A-Za-z_][\w.]*)\s*;/gm;
    let m;
    while ((m = re.exec(text)) !== null) targets.push(m[1]);
  } else if (lang === 'cpp-header' || lang === 'cpp-impl') {
    const reQuoted = /^#include\s+"([^"]+)"/gm;
    const reAngle = /^#include\s+<([^>]+)>/gm;
    let m;
    while ((m = reQuoted.exec(text)) !== null) targets.push(m[1]);
    while ((m = reAngle.exec(text)) !== null) targets.push(m[1]);
  } else if (lang === 'python') {
    const re1 = /^\s*import\s+([A-Za-z_][\w.]*)/gm;
    const re2 = /^\s*from\s+([A-Za-z_.][\w.]*)\s+import\s+/gm;
    let m;
    while ((m = re1.exec(text)) !== null) targets.push(m[1]);
    while ((m = re2.exec(text)) !== null) targets.push(m[1]);
  }
  return targets;
}

function topLevelDirOf(rel) {
  const ix = rel.indexOf('/');
  return ix < 0 ? './' : rel.slice(0, ix) + '/';
}

// Returns { rel, mod } when the import resolves to an in-repo file path,
// or { mod } when only the top-level module can be inferred,
// or null when the import is external/unresolvable.
function resolveImport(target, sourceRel, topLevelDirs, fileIndex) {
  // 0. C# namespace — `using Foo.Bar.Baz;` names a namespace, not a path. Resolve it
  //    against the namespace→file index built from each .cs file's `namespace` decl.
  //    A `using` imports a whole namespace, so the honest edge is module-level; a
  //    file-level edge is only emitted when the namespace maps to exactly one file.
  //    Match the longest known namespace that prefixes the target so a `using` on a
  //    leaf namespace still resolves when only an ancestor namespace is declared.
  if (fileIndex.byNamespace && fileIndex.byNamespace.size && !target.startsWith('.') && !target.includes('/')) {
    let nsHit = null;
    for (let ns = target; ns.includes('.'); ns = ns.slice(0, ns.lastIndexOf('.'))) {
      if (fileIndex.byNamespace.has(ns)) { nsHit = ns; break; }
    }
    if (!nsHit && fileIndex.byNamespace.has(target)) nsHit = target;
    if (nsHit) {
      const files = fileIndex.byNamespace.get(nsHit);
      const mod = topLevelDirOf(files[0]);
      // Only a single-file namespace yields an unambiguous file edge.
      if (files.length === 1) return { rel: files[0], mod };
      return { mod };
    }
    // A dotted target that resolves to no known namespace is an external package
    // (System.*, third-party) — fall through to the basename branch, which returns null.
  }
  // 1. Relative path — resolve against source dir.
  if (target.startsWith('.')) {
    const sourceDir = path.posix.dirname(sourceRel);
    const resolved = path.posix.normalize(path.posix.join(sourceDir, target));
    const hit = matchAgainstIndex(resolved, fileIndex);
    if (hit) return { rel: hit, mod: topLevelDirOf(hit) };
    return { mod: topLevelDirOf(resolved) };
  }
  // 2. Path with separator — try as repo-relative.
  if (target.includes('/')) {
    const hit = matchAgainstIndex(target, fileIndex);
    if (hit) return { rel: hit, mod: topLevelDirOf(hit) };
    // Match basename suffix — e.g. `openxr/openxr.h` finds `include/openxr/openxr.h`.
    const suffixHit = fileIndex.bySuffix.get(target);
    if (suffixHit && suffixHit.length === 1) return { rel: suffixHit[0], mod: topLevelDirOf(suffixHit[0]) };
    // Extensionless module path (Python `core/shape`, Go `proj/core`, Java `geo/core/Shape`):
    // try the path's last segments as a file basename across known extensions. Preferred over
    // the head-segment directory match below so a concrete FILE edge beats a folder edge.
    const ext = resolveExtensionlessPath(target, sourceRel, fileIndex, topLevelDirs);
    if (ext && ext.rel) return ext;
    // Head segment names a known top-level module → module-level edge.
    const headSegment = target.split('/')[0];
    const candidate = headSegment + '/';
    if (topLevelDirs.has(candidate)) return { mod: candidate };
    if (ext) return ext; // module-level fallback from the extensionless resolver
    return null;
  }
  // 3. Bare filename — look up by basename. Prefer same-module disambiguation.
  const base = target;
  let candidates = fileIndex.byBasename.get(base);
  // Extensionless bare module (e.g. a single-segment import): match basename sans extension.
  if (!candidates || !candidates.length) {
    const noExt = fileIndex.byBasenameNoExt && fileIndex.byBasenameNoExt.get(base);
    if (noExt && noExt.length) candidates = noExt;
  }
  if (!candidates || !candidates.length) return null;
  if (candidates.length === 1) return { rel: candidates[0], mod: topLevelDirOf(candidates[0]) };
  const sourceMod = topLevelDirOf(sourceRel);
  const sameModule = candidates.find((c) => topLevelDirOf(c) === sourceMod);
  if (sameModule) return { rel: sameModule, mod: sourceMod };
  return { rel: candidates[0], mod: topLevelDirOf(candidates[0]) };
}

function matchAgainstIndex(rel, fileIndex) {
  if (fileIndex.byRel.has(rel)) return rel;
  // ESM TS sources import the *compiled* `.js` form even when the source is `.ts` —
  // `import './envelope.js'` resolves to `envelope.ts`. Strip the suffix and re-try.
  const stripped = rel.replace(/\.(?:js|jsx|mjs|cjs)$/, '');
  const candidates = stripped !== rel ? [stripped, rel] : [rel];
  for (const base of candidates) {
    for (const ext of ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs']) {
      if (fileIndex.byRel.has(base + ext)) return base + ext;
      if (fileIndex.byRel.has(base + '/index' + ext)) return base + '/index' + ext;
    }
  }
  return null;
}

// Resolve an extensionless, `/`-separated module path (e.g. `core/shape`, `geo/core/Shape`)
// to an in-repo file. Strategy: walk the path's tails from longest to shortest, matching the
// basename (without extension) of the final segment, constrained by the preceding segment as
// a directory hint. Falls back to a directory (module-level) edge when only a folder matches.
function resolveExtensionlessPath(target, sourceRel, fileIndex, topLevelDirs) {
  const segs = target.split('/').filter(Boolean);
  if (!segs.length) return null;
  // Try the last segment as a file basename (sans extension). Disambiguate by requiring the
  // parent dir segment to appear in the file's path when more than one candidate matches.
  const last = segs[segs.length - 1];
  const parent = segs.length >= 2 ? segs[segs.length - 2] : null;
  const byNoExt = fileIndex.byBasenameNoExt.get(last);
  if (byNoExt && byNoExt.length) {
    let cands = byNoExt;
    if (cands.length > 1 && parent) {
      const narrowed = cands.filter((r) => r.split('/').includes(parent));
      if (narrowed.length) cands = narrowed;
    }
    if (cands.length === 1) return { rel: cands[0], mod: topLevelDirOf(cands[0]) };
    // Multiple: prefer same module as the source, else module-level edge to the first.
    const srcMod = topLevelDirOf(sourceRel);
    const same = cands.find((r) => topLevelDirOf(r) === srcMod);
    if (same) return { rel: same, mod: srcMod };
    return { mod: topLevelDirOf(cands[0]) };
  }
  // No file basename matched — the last segment may name a package DIRECTORY (Go/Java
  // style). If exactly one indexed file lives directly under a dir of that name, treat it
  // as the file edge; otherwise fall back to a module-level edge.
  const dirHit = fileIndex.byDir.get(last);
  if (dirHit && dirHit.length === 1) return { rel: dirHit[0], mod: topLevelDirOf(dirHit[0]) };
  if (dirHit && dirHit.length > 1) return { mod: topLevelDirOf(dirHit[0]) };
  // Else try each segment as a top-level directory (module edge).
  for (const s of segs) {
    if (topLevelDirs.has(s + '/')) return { mod: s + '/' };
  }
  return null;
}

// `namespaceByRel` (optional) maps `rel` → declared namespace string, used to build the
// C# namespace→files index that `resolveImport` consults for `using` directives.
function buildFileIndex(files, namespaceByRel) {
  const byRel = new Set();
  const byBasename = new Map();
  const byBasenameNoExt = new Map();
  const byDir = new Map(); // immediate-parent-dir name → files directly within it
  const bySuffix = new Map();
  const byNamespace = new Map();
  for (const f of files) {
    byRel.add(f.rel);
    const base = path.posix.basename(f.rel);
    if (!byBasename.has(base)) byBasename.set(base, []);
    byBasename.get(base).push(f.rel);
    const baseNoExt = base.replace(/\.[^.]+$/, '');
    if (!byBasenameNoExt.has(baseNoExt)) byBasenameNoExt.set(baseNoExt, []);
    byBasenameNoExt.get(baseNoExt).push(f.rel);
    // Index two- and three-segment suffixes so `openxr/openxr.h` matches `include/openxr/openxr.h`.
    const parts = f.rel.split('/');
    if (parts.length >= 2) {
      const dirName = parts[parts.length - 2];
      if (!byDir.has(dirName)) byDir.set(dirName, []);
      byDir.get(dirName).push(f.rel);
    }
    for (let depth = 2; depth <= 3 && depth <= parts.length; depth++) {
      const suf = parts.slice(parts.length - depth).join('/');
      if (!bySuffix.has(suf)) bySuffix.set(suf, []);
      bySuffix.get(suf).push(f.rel);
    }
    const ns = namespaceByRel && namespaceByRel.get(f.rel);
    if (ns) {
      if (!byNamespace.has(ns)) byNamespace.set(ns, []);
      byNamespace.get(ns).push(f.rel);
    }
  }
  return { byRel, byBasename, byBasenameNoExt, byDir, bySuffix, byNamespace };
}

function detectEntryPoints(root, files) {
  const entries = [];
  try {
    const pkg = path.join(root, 'package.json');
    if (fs.existsSync(pkg)) {
      const j = JSON.parse(fs.readFileSync(pkg, 'utf8'));
      for (const key of ['main', 'module']) {
        if (j[key]) entries.push({ rel: j[key], role: `package.json ${key}` });
      }
      if (j.bin) {
        const bins = typeof j.bin === 'string' ? { [j.name || 'bin']: j.bin } : j.bin;
        for (const [k, v] of Object.entries(bins)) entries.push({ rel: v, role: `bin: ${k}` });
      }
    }
  } catch {}
  const csprojs = files.filter((f) => f.rel.endsWith('.csproj') && !f.rel.includes('/'));
  for (const cs of csprojs) {
    try {
      const text = fs.readFileSync(cs.abs, 'utf8');
      const m = text.match(/<StartupObject>([^<]+)<\/StartupObject>/);
      if (m) entries.push({ rel: cs.rel, role: `StartupObject: ${m[1]}` });
    } catch {}
  }
  for (const f of files) {
    if (/(?:^|\/)(Program|Main)\.cs$/i.test(f.rel)) entries.push({ rel: f.rel, role: 'C# entry' });
    if (/^src\/(main|index)\.(ts|tsx|js|jsx|mjs)$/.test(f.rel)) entries.push({ rel: f.rel, role: 'SPA entry' });
  }
  const seen = new Set();
  return entries.filter((e) => { if (seen.has(e.rel)) return false; seen.add(e.rel); return true; });
}

function loadPreviousCodemap(codemapPath) {
  if (!fs.existsSync(codemapPath)) return null;
  return fs.readFileSync(codemapPath, 'utf8');
}

function diffSummary(prev, current) {
  if (!prev) return { initial: true };
  const prevFiles = new Set([...prev.matchAll(/^-\s+`([^`]+)`/gm)].map((m) => m[1]));
  const curFiles = new Set([...current.matchAll(/^-\s+`([^`]+)`/gm)].map((m) => m[1]));
  let added = 0, removed = 0;
  for (const f of curFiles) if (!prevFiles.has(f)) added++;
  for (const f of prevFiles) if (!curFiles.has(f)) removed++;
  return { added, removed };
}

// ----- LLM-facing prose section helpers -----
// These build the # Architecture header (Overview, Modules, Conventions, Hubs)
// that ships above the structured sections consumed by codemap-visualize.

function readReadmeH1(root) {
  try {
    const readme = path.join(root, 'README.md');
    if (!fs.existsSync(readme)) return '';
    const text = fs.readFileSync(readme, 'utf8');
    const lines = text.split(/\r?\n/);
    const h1Index = lines.findIndex((l) => /^#\s+/.test(l));
    if (h1Index < 0) return '';
    // First paragraph after H1, skipping blank lines.
    const para = [];
    for (let i = h1Index + 1; i < Math.min(lines.length, h1Index + 30); i++) {
      const l = lines[i].trim();
      if (!l) { if (para.length) break; else continue; }
      if (/^#/.test(l)) break;
      para.push(l);
    }
    return para.join(' ').trim();
  } catch { return ''; }
}

function readPackageDescription(root) {
  try {
    const pkg = path.join(root, 'package.json');
    if (fs.existsSync(pkg)) {
      const j = JSON.parse(fs.readFileSync(pkg, 'utf8'));
      if (j.description) return String(j.description).trim();
    }
  } catch {}
  // Walk one level deep for a nested package.json description (e.g. server/package.json).
  try {
    const entries = fs.readdirSync(root, { withFileTypes: true });
    for (const ent of entries) {
      if (!ent.isDirectory() || SKIP_DIRS.has(ent.name)) continue;
      const p = path.join(root, ent.name, 'package.json');
      if (fs.existsSync(p)) {
        try {
          const j = JSON.parse(fs.readFileSync(p, 'utf8'));
          if (j.description) return String(j.description).trim();
        } catch {}
      }
    }
  } catch {}
  return '';
}

function dominantLanguage(groups) {
  const counts = new Map();
  for (const items of groups.values()) {
    for (const it of items) {
      const ext = path.extname(it.rel).toLowerCase();
      const lang = LANG_BY_EXT[ext];
      if (!lang) continue;
      counts.set(lang, (counts.get(lang) || 0) + 1);
    }
  }
  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  return sorted.length ? sorted[0][0] : '';
}

const ROLE_BY_MODULE_NAME = {
  'server/': 'TypeScript MCP server',
  'unity-package/': 'Unity Editor extension',
  'src/': 'application source',
  'lib/': 'library code',
  'app/': 'application code',
  'apps/': 'application code',
  'packages/': 'monorepo packages',
  'scripts/': 'build/automation scripts',
  'tools/': 'developer tools',
  'tests/': 'test suite',
  'test/': 'test suite',
  'docs/': 'documentation',
  'skills/': 'Claude Code skills',
  'agents/': 'Claude Code subagents',
  'hooks/': 'Claude Code hooks',
  'mcps/': 'MCP servers',
  '.github/': 'GitHub config',
};

function inferModuleRole(modName, items) {
  const hardcoded = ROLE_BY_MODULE_NAME[modName];
  if (hardcoded) return hardcoded;
  // Fallback: derive from highest-inbound-edge file's purpose, else humanize the folder name.
  if (items.length) {
    const sorted = [...items].sort((a, b) => (b.inboundCount || 0) - (a.inboundCount || 0));
    if (sorted[0] && sorted[0].purpose && sorted[0].purpose !== '<vendored>') return sorted[0].purpose;
  }
  return modName.replace(/\/$/, '').replace(/[-_]+/g, ' ');
}

function inferModulePurpose(items, inboundCounts) {
  // 2-3 most-imported files' purposes, concatenated. Falls back to top-by-export-count.
  const ranked = items
    .map((it) => ({ ...it, _in: inboundCounts.get(it.rel) || 0 }))
    .filter((it) => it.purpose && it.purpose !== '<vendored>')
    .sort((a, b) => b._in - a._in || (b.exports?.length || 0) - (a.exports?.length || 0));
  const top = ranked.slice(0, 3).map((it) => it.purpose);
  // Dedupe purpose lines; some files share the same one-liner.
  const seen = new Set();
  const unique = [];
  for (const p of top) {
    const k = p.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    unique.push(p);
  }
  return unique.join('. ');
}

function findModuleEntry(modName, items, entryPoints) {
  const inModule = entryPoints.find((e) => topLevelDirOf(e.rel) === modName);
  if (inModule) return inModule.rel;
  const candidates = ['index.ts', 'index.js', 'index.mjs', 'Boot.cs', 'Main.cs', 'Program.cs'];
  for (const c of candidates) {
    const direct = items.find((it) => path.posix.basename(it.rel) === c && it.rel.split('/').length === 2);
    if (direct) return direct.rel;
  }
  return '';
}

function computeInboundCounts(fileEdges) {
  const inbound = new Map();
  for (const targets of fileEdges.values()) {
    for (const t of targets) inbound.set(t, (inbound.get(t) || 0) + 1);
  }
  return inbound;
}

function computeModuleImportedBy(moduleEdges) {
  const inv = new Map();
  for (const [from, bucket] of moduleEdges.entries()) {
    for (const to of bucket.keys()) {
      if (!inv.has(to)) inv.set(to, new Set());
      inv.get(to).add(from);
    }
  }
  return inv;
}

function publicSurfaceForModule(items, inboundCounts) {
  // Rank files by inbound, take exports[0..2] from each. Cap at 10 total entries.
  const ranked = [...items]
    .filter((it) => it.exports && it.exports.length)
    .map((it) => ({ ...it, _in: inboundCounts.get(it.rel) || 0 }));
  const hasEdges = ranked.some((it) => it._in > 0);
  ranked.sort((a, b) => hasEdges
    ? (b._in - a._in) || a.rel.localeCompare(b.rel)
    : a.rel.localeCompare(b.rel));
  const surface = [];
  for (const it of ranked) {
    for (const e of it.exports.slice(0, 3)) {
      // Trim signature tail (` — sig`) to keep public surface readable.
      const name = e.name.replace(/\s+—\s+.*$/, '').replace(/^default:\s+/, '');
      surface.push(name);
      if (surface.length >= 10) break;
    }
    if (surface.length >= 10) break;
  }
  // Dedupe while preserving order.
  const seen = new Set();
  return surface.filter((s) => { if (seen.has(s)) return false; seen.add(s); return true; });
}

function computeInternals(modName, items, inboundCounts) {
  // Group files by immediate sub-folder (between modName/ and basename).
  // Emit only sub-folders with ≥2 files.
  const bySubfolder = new Map();
  for (const it of items) {
    const rest = it.rel.slice(modName.length); // strips "module/"
    const parts = rest.split('/');
    if (parts.length < 2) continue; // file is directly in module/
    const sub = parts[0];
    if (!bySubfolder.has(sub)) bySubfolder.set(sub, []);
    bySubfolder.get(sub).push(it);
  }
  const lines = [];
  const sortedSubs = [...bySubfolder.keys()].sort();
  for (const sub of sortedSubs) {
    const subItems = bySubfolder.get(sub);
    if (subItems.length < 2) continue;
    const topItem = [...subItems].sort((a, b) => (inboundCounts.get(b.rel) || 0) - (inboundCounts.get(a.rel) || 0))[0];
    const purpose = topItem && topItem.purpose && topItem.purpose !== '<vendored>'
      ? topItem.purpose
      : `${subItems.length} files`;
    lines.push(`${modName}${sub}/ — ${purpose}`);
  }
  return lines;
}

function detectConventions(groups) {
  // Evidence-based: only fire for ≥3-instance explicit markers (implements/extends/attribute).
  const impl = new Map();   // interface -> [{name, file}]
  const ext = new Map();    // base class -> [{name, file}]
  const attr = new Map();   // attribute -> [{name, file}]

  for (const items of groups.values()) {
    for (const it of items) {
      if (!it.classes) continue;
      for (const c of it.classes) {
        for (const i of (c.implements || [])) {
          const key = normalizeTypeRef(i);
          if (!impl.has(key)) impl.set(key, []);
          impl.get(key).push({ name: c.name, file: it.rel });
        }
        for (const e of (c.extends || [])) {
          const key = normalizeTypeRef(e);
          if (!ext.has(key)) ext.set(key, []);
          ext.get(key).push({ name: c.name, file: it.rel });
        }
        for (const a of (c.attributes || [])) {
          if (!attr.has(a)) attr.set(a, []);
          attr.get(a).push({ name: c.name, file: it.rel });
        }
      }
    }
  }

  const conventions = [];
  const examplesOf = (entries) => entries.slice(0, 3).map((e) => `\`${e.name}\``).join(', ');

  for (const [iface, entries] of impl.entries()) {
    if (entries.length < 3) continue;
    if (!iface) continue;
    conventions.push({
      kind: 'implements',
      name: `Implements ${iface}`,
      count: entries.length,
      detail: `tool/handler convention, e.g. ${examplesOf(entries)}`,
    });
  }
  for (const [base, entries] of ext.entries()) {
    if (entries.length < 3) continue;
    if (!base) continue;
    if (/^(Error|Exception|object)$/.test(base)) continue;
    conventions.push({
      kind: 'extends',
      name: `Extends ${base}`,
      count: entries.length,
      detail: `subclass family, e.g. ${examplesOf(entries)}`,
    });
  }
  for (const [a, entries] of attr.entries()) {
    if (entries.length < 3) continue;
    conventions.push({
      kind: 'attribute',
      name: `Carries [${a}] attribute`,
      count: entries.length,
      detail: `reflection-discoverable marker, e.g. ${examplesOf(entries)}`,
    });
  }

  conventions.sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  return conventions;
}

async function main() {
  const args = parseArgs(process.argv);
  const root = args.root;
  if (!fs.existsSync(root)) { console.error(`root not found: ${root}`); process.exit(1); }

  log(args, `root: ${root}`);
  const projectName = readProjectName(root);
  log(args, `project: ${projectName}`);

  const config = loadConfig(root);
  const configRegexes = config.skipPatterns.map(configGlobToRegex);
  if (config.skipPatterns.length) log(args, `config: ${config.skipPatterns.length} skip patterns`);

  const allFiles = walk(root, configRegexes);
  log(args, `scanned: ${allFiles.length} files`);

  // Tree-sitter readiness: probe once. When the optional deps aren't installed this is
  // null and every AST language falls back to regex (or empty) — graceful degradation.
  const hasAstLang = allFiles.some((f) => isTreeSitterLang(LANG_BY_EXT[path.extname(f.rel).toLowerCase()] || 'other')
    || TREE_SITTER_TAG[LANG_BY_EXT[path.extname(f.rel).toLowerCase()] || 'other']);
  let treeSitterReady = false;
  if (hasAstLang) {
    treeSitterReady = (await initTreeSitter()) !== null;
    if (!treeSitterReady) {
      log(args, 'tree-sitter deps not installed — AST languages fall back to regex/empty. ' +
        'Run `npm install` in skills/update-codemap for full multi-language coverage.');
    }
  }

  const vendoredRegexes = config.vendoredPatterns.map(configGlobToRegex);
  const isVendored = (rel) => vendoredRegexes.some((re) => re.test(rel));

  const groups = new Map();
  const moduleImports = new Map();
  // Collected during the scan; feeds the C# namespace→file index that resolveImport
  // consults for `using` directives. Built after the loop so heads are read once.
  const namespaceByRel = new Map();

  for (const f of allFiles) {
    const ext = path.extname(f.rel).toLowerCase();
    const lang = LANG_BY_EXT[ext] || 'other';
    const head = readHead(f.abs, READ_CAP_LINES);
    if (isGenerated(head.lines)) continue;

    const vendored = isVendored(f.rel);

    let exports = [];
    let classes = [];
    let text = head.text;
    let astImports = null; // non-null when the tree-sitter engine supplied imports

    const tsTag = TREE_SITTER_TAG[lang];
    if (!vendored && tsTag && treeSitterReady) {
      // AST languages get the FULL file — declarations past the head-cap matter.
      const full = readFull(f.abs);
      const ast = await extractWithTreeSitter(full, tsTag);
      if (ast) {
        text = full;
        exports = ast.exports;
        classes = ast.classes;
        astImports = ast.imports;
      }
    }

    // Regex extraction: primary for ts/csharp, and the fallback for cpp when the AST
    // engine was unavailable or returned null (classes still empty here).
    if (!vendored && classes.length === 0 && exports.length === 0 &&
        (lang === 'ts' || lang === 'csharp' || lang === 'cpp-header')) {
      if (head.totalLines > READ_CAP_LINES && text === head.text) {
        const extended = readHead(f.abs, READ_CAP_EXTENDED);
        text = extended.text;
      }
      if (lang === 'ts') { exports = extractExportsTs(text); classes = extractClassesTs(text); }
      else if (lang === 'csharp') { exports = extractExportsCSharp(text); classes = extractClassesCSharp(text); }
      else if (lang === 'cpp-header') { exports = extractExportsCppHeader(text); classes = extractClassesCpp(text); }
    }

    const purpose = vendored ? '<vendored>' : derivePurpose(head.lines, f.rel);
    const top = topLevelDirOf(f.rel);
    if (!groups.has(top)) groups.set(top, []);
    groups.get(top).push({ rel: f.rel, purpose, exports, classes, vendored });

    if (!vendored) {
      // Prefer AST-extracted imports; else regex. (cpp-impl has no AST classes but its
      // includes still come through the engine when ready.)
      const targets = astImports !== null ? astImports : extractImports(text, lang);
      if (targets.length) moduleImports.set(f.rel, targets);
    }

    // C# namespace declaration → index entry, so `using` directives in other files
    // resolve to this file's module. Non-vendored .cs only; a file may declare a
    // namespace without exporting a class, so this is independent of `classes`.
    if (!vendored && lang === 'csharp') {
      const nsMatch = text.match(/^\s*namespace\s+([A-Za-z_][\w.]*)\s*[;{]/m);
      if (nsMatch) namespaceByRel.set(f.rel, nsMatch[1]);
    }
  }

  const fileIndex = buildFileIndex(allFiles, namespaceByRel);
  const topLevelDirs = new Set(groups.keys());

  // Edges. Two layers:
  //   moduleEdges[from][to] = count           (weighted, for ## Dependencies)
  //   fileEdges[from] = Set<targetRel>        (for ## File deps)
  const moduleEdges = new Map();
  const fileEdges = new Map();
  for (const [sourceRel, targets] of moduleImports.entries()) {
    const sourceMod = topLevelDirOf(sourceRel);
    for (const t of targets) {
      const resolved = resolveImport(t, sourceRel, topLevelDirs, fileIndex);
      if (!resolved) continue;
      const targetMod = resolved.mod;
      if (!targetMod) continue;
      if (resolved.rel && resolved.rel !== sourceRel) {
        if (!fileEdges.has(sourceRel)) fileEdges.set(sourceRel, new Set());
        fileEdges.get(sourceRel).add(resolved.rel);
      }
      if (targetMod === sourceMod) continue;
      if (!moduleEdges.has(sourceMod)) moduleEdges.set(sourceMod, new Map());
      const bucket = moduleEdges.get(sourceMod);
      bucket.set(targetMod, (bucket.get(targetMod) || 0) + 1);
    }
  }

  const entryPoints = detectEntryPoints(root, allFiles);

  const today = new Date().toISOString().slice(0, 10);

  // ----- LLM-facing prose header (Overview, Modules, Conventions, Hubs).
  // Section ordering is load-bearing: prose first, then the structured sections
  // consumed by codemap-visualize. The visualize parser keys on `## <name>/`
  // for groups and on a fixed set of named sections (Entry points, Layers,
  // Dependencies, File deps, Class graph) — anything else is benign noise.
  const inboundCounts = computeInboundCounts(fileEdges);
  const importedBy = computeModuleImportedBy(moduleEdges);
  const readmeH1 = readReadmeH1(root);
  const pkgDesc = readPackageDescription(root);
  const domLang = dominantLanguage(groups);

  let out = `# Architecture — ${projectName}\nLast updated: ${today}\n\n`;

  // ## Overview
  const overviewParts = [];
  const ensurePeriod = (s) => /[.!?]$/.test(s.trim()) ? s.trim() : (s.trim() + '.');
  if (readmeH1) overviewParts.push(ensurePeriod(readmeH1));
  else if (pkgDesc) overviewParts.push(ensurePeriod(pkgDesc));
  else overviewParts.push(`${projectName} — codemap-derived architecture summary.`);
  if (entryPoints.length) {
    overviewParts.push(`Entry: ${entryPoints.slice(0, 2).map((e) => `\`${e.rel}\``).join(', ')}.`);
  }
  if (domLang) overviewParts.push(`Dominant language: ${domLang}.`);
  out += `## Overview\n${overviewParts.join(' ')}\n\n`;

  // ## Modules
  const sortedModuleNames = [...groups.keys()].sort();
  if (sortedModuleNames.length) {
    out += `## Modules\n`;
    for (const modName of sortedModuleNames) {
      const items = groups.get(modName);
      const role = inferModuleRole(modName, items);
      const purpose = inferModulePurpose(items, inboundCounts);
      const entry = findModuleEntry(modName, items, entryPoints);
      const surface = publicSurfaceForModule(items, inboundCounts);
      const depsOn = moduleEdges.has(modName)
        ? [...moduleEdges.get(modName).keys()].sort()
        : [];
      const impBy = importedBy.has(modName)
        ? [...importedBy.get(modName)].sort()
        : [];
      const internals = computeInternals(modName, items, inboundCounts);

      out += `### ${modName}\n`;
      out += `**Role:** ${role}\n`;
      if (purpose) out += `**Purpose:** ${purpose}\n`;
      if (entry) out += `**Entry:** \`${entry}\`\n`;
      if (surface.length) out += `**Public surface:** ${surface.map((s) => `\`${s}\``).join(', ')}\n`;
      if (depsOn.length) out += `**Depends on:** ${depsOn.join(', ')}\n`;
      if (impBy.length) out += `**Imported by:** ${impBy.join(', ')}\n`;
      if (internals.length) {
        out += `**Internals:**\n`;
        for (const line of internals) out += `- ${line}\n`;
      }
      out += `\n`;
    }
  }

  // ## Conventions detected — only fire for ≥3-instance explicit markers.
  const conventions = detectConventions(groups);
  if (conventions.length) {
    out += `## Conventions detected\n`;
    for (const c of conventions) {
      out += `- ${c.name}: ${c.count} instances — ${c.detail}\n`;
    }
    out += `\n`;
  }

  // ## Hubs — files with ≥3 inbound file-edges, ranked by importer count.
  const hubEntries = [];
  for (const [file, count] of inboundCounts.entries()) {
    if (count < 3) continue;
    // Find purpose by scanning groups.
    let purpose = '';
    for (const items of groups.values()) {
      const hit = items.find((it) => it.rel === file);
      if (hit) { purpose = hit.purpose; break; }
    }
    hubEntries.push({ file, count, purpose });
  }
  hubEntries.sort((a, b) => b.count - a.count || a.file.localeCompare(b.file));
  if (hubEntries.length) {
    out += `## Hubs\n`;
    for (const h of hubEntries) {
      const tail = h.purpose ? `, role: ${h.purpose}` : '';
      out += `- \`${h.file}\` — ${h.count} importers${tail}\n`;
    }
    out += `\n`;
  }

  if (entryPoints.length) {
    out += `## Entry points\n`;
    for (const e of entryPoints) out += `- \`${e.rel}\` — ${e.role}\n`;
    out += `\n`;
  }
  if (config.layers.length) {
    out += `## Layers\n`;
    for (const l of config.layers) out += `- ${l.name}: ${l.modules.join(', ')}\n`;
    out += `\n`;
  }
  if (moduleEdges.size) {
    out += `## Dependencies\n`;
    const sortedSources = [...moduleEdges.keys()].sort();
    for (const s of sortedSources) {
      // Sort by weight desc, then name asc, and render `target (N)`.
      const entries = [...moduleEdges.get(s).entries()]
        .sort((a, b) => (b[1] - a[1]) || a[0].localeCompare(b[0]));
      const rendered = entries.map(([t, w]) => `${t} (${w})`).join(', ');
      out += `- ${s} → ${rendered}\n`;
    }
    out += `\n`;
  }
  if (fileEdges.size) {
    out += `## File deps\n`;
    const sortedSources = [...fileEdges.keys()].sort();
    for (const s of sortedSources) {
      const targets = [...fileEdges.get(s)].sort();
      out += `- \`${s}\` → ${targets.map((t) => `\`${t}\``).join(', ')}\n`;
    }
    out += `\n`;
  }

  // Phase 1c: ## Class graph — class-level data for UML rendering and convention detection.
  // Block-per-class shape: parser keys off "- class:" / "- interface:" / "- struct:" / "- record:" / "- enum:".
  // Sub-lines (indented 2 spaces) carry attributes; each starts with a stable keyword followed by ":".
  const allClassEntries = [];
  for (const [g, items] of groups.entries()) {
    for (const it of items) {
      if (!it.classes || !it.classes.length) continue;
      for (const c of it.classes) {
        allClassEntries.push({ file: it.rel, module: g, ...c });
      }
    }
  }
  if (allClassEntries.length) {
    out += `## Class graph\n`;
    const sorted = allClassEntries.sort((a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name));
    for (const c of sorted) {
      out += `- ${c.kind}: \`${c.name}\` in \`${c.file}\`\n`;
      if (c.namespace) out += `  namespace: ${c.namespace}\n`;
      if (c.extends.length) out += `  extends: ${c.extends.join(' ; ')}\n`;
      if (c.implements.length) out += `  implements: ${c.implements.join(' ; ')}\n`;
      if (c.attributes.length) out += `  attributes: ${c.attributes.join(' ; ')}\n`;
      if (c.fields.length) {
        const renderedFields = c.fields.map((f) => `${f.name}: ${f.type}`).join(' ; ');
        out += `  fields: ${renderedFields}\n`;
      }
    }
    out += `\n`;
  }

  const sortedGroups = [...groups.keys()].sort();
  for (const g of sortedGroups) {
    out += `## ${g}\n`;
    const items = groups.get(g).sort((a, b) => a.rel.localeCompare(b.rel));
    for (const it of items) {
      out += `- \`${it.rel}\` — ${it.purpose}\n`;
      if (it.exports.length) {
        // Separator is ` ; ` (not `, `) because TS/C# signatures contain commas
        // inside parameter lists, generics, and tuple types. Visualize splits on the same token.
        out += `  exports: ${it.exports.map((e) => e.name).join(' ; ')}\n`;
      }
    }
    out += `\n`;
  }

  const codemapPath = path.join(root, '.claude', 'codemap.md');
  const dirtyPath = path.join(root, '.claude', 'codemap.dirty');
  let dirtyClearedFrom = null;
  if (fs.existsSync(dirtyPath)) {
    try { dirtyClearedFrom = fs.readFileSync(dirtyPath, 'utf8').trim(); } catch {}
  }

  if (args.dryRun) {
    log(args, '--- dry-run output ---');
    process.stdout.write(out);
    log(args, '--- end ---');
    return;
  }

  fs.mkdirSync(path.dirname(codemapPath), { recursive: true });
  const prev = loadPreviousCodemap(codemapPath);
  fs.writeFileSync(codemapPath, out);
  if (dirtyClearedFrom !== null) {
    try { fs.unlinkSync(dirtyPath); } catch {}
  }

  const diff = diffSummary(prev, out);
  if (diff.initial) {
    const exported = [...groups.values()].flat().filter((it) => it.exports.length).length;
    log(args, `initial scan: ${allFiles.length} files, ${exported} with exports across ${sortedGroups.length} top-level groups`);
  } else {
    log(args, `+ ${diff.added} files added`);
    log(args, `- ${diff.removed} files removed`);
  }
  if (config.skipPatterns.length) log(args, `config applied: ${config.skipPatterns.length} skip patterns from .claude/codemap.config.md`);
  if (config.warnings.length) {
    log(args, `warnings (malformed config lines, ignored):`);
    for (const w of config.warnings) log(args, `  - line ${w.line}: ${w.text}`);
  }
  if (dirtyClearedFrom !== null) log(args, `dirty sentinel cleared (last marked: ${dirtyClearedFrom})`);
  log(args, `wrote ${path.relative(root, codemapPath)}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
